- name: Configuring newly created EC2 instances
  hosts: all
  user: ubuntu
  roles:
    - role: weareinteractive.environment
      become: yes
    - role: setup
    - role: deploy_backend
  vars:
    environment_file_owner: ubuntu
    environment_file_group: ubuntu
    environment_config:
      NODE_ENV: production
      ENVIRONMENT: production
      TYPEORM_CONNECTION: postgres
      TYPEORM_ENTITIES: ~/backend_app/modules/domain/**/*.entity.js
      TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"