version: 2.1

jobs:
  build_backend:
    docker:
      - image: circleci/node:14.11.0
    steps:
      - checkout
      - run: npm i --prefix backend
      - run: npm run lint --prefix backend

  build_frontend:
    docker:
      - image: circleci/node:14.11.0
    steps:
      - checkout
      - run: npm i --prefix frontend
      - run: npm run lint --prefix frontend

  test_backend:
    docker:
      - image: circleci/node:14.11.0
    steps:
      - checkout
      - run: npm i --prefix backend
      - run: npm run test --prefix backend

  test_frontend:
    docker:
      - image: circleci/node:14.11.0
    steps:
      - checkout
      - run: npm i --prefix frontend
      - run: npm run test --prefix frontend

  analyze_backend:
    docker:
      - image: circleci/node:14.11.0
    steps:
      - checkout
      - run: npm audit --audit-level=critical --prefix backend

  analyze_frontend:
    docker:
      - image: circleci/node:14.11.0
    steps:
      - checkout
      - run: npm audit --audit-level=critical --prefix frontend

workflows:
  my_workflow:
    jobs:
      - build_backend
      - build_frontend
      - test_backend:
          requires:
            - build_backend
      - test_frontend:
          requires:
            - build_frontend
      - analyze_backend:
          requires:
            - test_backend
      - analyze_frontend:
          requires:
            - test_frontend