- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install node dependencies."
  become: yes
  apt:
    name: [ "nodejs", "npm" ]
    state: latest
    update_cache: yes

- name: "Install zip utility."
  become: yes
  apt:
    name: [ "zip", "unzip" ]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Set environment variables"
  become: yes
  shell: |
    echo "ENVIRONMENT=production" >> /etc/environment
    echo "TYPEORM_CONNECTION=postgres" >> /etc/environment
    echo "TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts" >> /etc/environment
    echo "TYPEORM_HOST=udacity-postgres.cbhggy4kae9x.eu-central-1.rds.amazonaws.com" >> /etc/environment
    echo "TYPEORM_PORT=5532" >> /etc/environment
    echo "TYPEORM_USERNAME=postgres" >> /etc/environment
    echo "TYPEORM_PASSWORD=HfLH3mk7elsAhod08r8n" >> /etc/environment
    echo "TYPEORM_DATABASE=udacity_database" >> /etc/environment

